// partidos.js - Calendario Maestro Completo (104 partidos estructurados)
// Horarios con zona horaria real de la sede. La página los muestra en la hora local del navegador; en México se verán en hora local de México.
// local/visit se muestran en español; localApi/visitApi se usan para API-Football.
const partidosMundial = [
    // ==========================================
    // FASE DE GRUPOS (72 Partidos con Códigos ISO)
    // ==========================================
    // --- GRUPO A ---
    { id: 'a1', local: 'México', localFlag: 'MX', visit: 'Sudáfrica', visitFlag: 'ZA', sede: 'Estadio Azteca', hora: '2026-06-11T13:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'A' , apiFixtureId: 66456904, localApi: 'Mexico', visitApi: 'South Africa' },
    { id: 'a2', local: 'Corea del Sur', localFlag: 'KR', visit: 'Chequia', visitFlag: 'CZ', sede: 'Estadio Guadalajara', hora: '2026-06-11T20:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'A' , apiFixtureId: 66456906, localApi: 'South Korea', visitApi: 'Czechia' },
    { id: 'a3', local: 'Chequia', localFlag: 'CZ', visit: 'Sudáfrica', visitFlag: 'ZA', sede: 'Estadio Atlanta', hora: '2026-06-18T12:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'A' , apiFixtureId: 66456910, localApi: 'Czechia', visitApi: 'South Africa' },
    { id: 'a4', local: 'México', localFlag: 'MX', visit: 'Corea del Sur', visitFlag: 'KR', sede: 'Estadio Guadalajara', hora: '2026-06-18T19:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'A' , apiFixtureId: 66456908, localApi: 'Mexico', visitApi: 'South Korea' },
    { id: 'a5', local: 'Chequia', localFlag: 'CZ', visit: 'México', visitFlag: 'MX', sede: 'Estadio Azteca', hora: '2026-06-24T19:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'A' , apiFixtureId: 66456912, localApi: 'Czechia', visitApi: 'Mexico' },
    { id: 'a6', local: 'Sudáfrica', localFlag: 'ZA', visit: 'Corea del Sur', visitFlag: 'KR', sede: 'Estadio Monterrey', hora: '2026-06-24T19:00-06:00', sedeTimezone: 'America/Monterrey', fase: 'grupos', grupo: 'A' , apiFixtureId: 66456914, localApi: 'South Africa', visitApi: 'South Korea' },

    // --- GRUPO B ---
    { id: 'b1', local: 'Canadá', localFlag: 'CA', visit: 'Bosnia', visitFlag: 'BA', sede: 'Estadio Toronto', hora: '2026-06-12T15:00-04:00', sedeTimezone: 'America/Toronto', fase: 'grupos', grupo: 'B' , apiFixtureId: 66456916, localApi: 'Canada', visitApi: 'Bosnia and Herzegovina' },
    { id: 'b2', local: 'Catar', localFlag: 'QA', visit: 'Suiza', visitFlag: 'CH', sede: 'Estadio San Francisco', hora: '2026-06-13T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'B' , apiFixtureId: 66456918, localApi: 'Qatar', visitApi: 'Switzerland' },
    { id: 'b3', local: 'Canadá', localFlag: 'CA', visit: 'Catar', visitFlag: 'QA', sede: 'Estadio Vancouver', hora: '2026-06-18T15:00-07:00', sedeTimezone: 'America/Vancouver', fase: 'grupos', grupo: 'B' , apiFixtureId: 66456920, localApi: 'Canada', visitApi: 'Qatar' },
    { id: 'b4', local: 'Suiza', localFlag: 'CH', visit: 'Bosnia', visitFlag: 'BA', sede: 'Estadio Los Angeles', hora: '2026-06-18T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'B' , apiFixtureId: 66456922, localApi: 'Switzerland', visitApi: 'Bosnia and Herzegovina' },
    { id: 'b5', local: 'Suiza', localFlag: 'CH', visit: 'Canadá', visitFlag: 'CA', sede: 'Estadio Vancouver', hora: '2026-06-24T12:00-07:00', sedeTimezone: 'America/Vancouver', fase: 'grupos', grupo: 'B' , apiFixtureId: 66456924, localApi: 'Switzerland', visitApi: 'Canada' },
    { id: 'b6', local: 'Bosnia', localFlag: 'BA', visit: 'Catar', visitFlag: 'QA', sede: 'Estadio Boston', hora: '2026-06-24T15:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'B' , apiFixtureId: 66456926, localApi: 'Bosnia and Herzegovina', visitApi: 'Qatar' },

    // --- GRUPO C ---
    { id: 'c1', local: 'Brasil', localFlag: 'BR', visit: 'Marruecos', visitFlag: 'MA', sede: 'Estadio New York', hora: '2026-06-13T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'C' , apiFixtureId: 66456928, localApi: 'Brazil', visitApi: 'Morocco' },
    { id: 'c2', local: 'Escocia', localFlag: 'GB-SCT', visit: 'Haití', visitFlag: 'HT', sede: 'Estadio Boston', hora: '2026-06-13T21:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'C' , apiFixtureId: 66456930, localApi: 'Scotland', visitApi: 'Haiti' },
    { id: 'c3', local: 'Escocia', localFlag: 'GB-SCT', visit: 'Marruecos', visitFlag: 'MA', sede: 'Estadio Boston', hora: '2026-06-19T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'C' , apiFixtureId: 66456934, localApi: 'Scotland', visitApi: 'Morocco' },
    { id: 'c4', local: 'Brasil', localFlag: 'BR', visit: 'Haití', visitFlag: 'HT', sede: 'Estadio Philadelphia', hora: '2026-06-19T20:30-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'C' , apiFixtureId: 66456932, localApi: 'Brazil', visitApi: 'Haiti' },
    { id: 'c5', local: 'Marruecos', localFlag: 'MA', visit: 'Haití', visitFlag: 'HT', sede: 'Estadio Orlando', hora: '2026-06-24T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'C' , apiFixtureId: 66456938, localApi: 'Morocco', visitApi: 'Haiti' },
    { id: 'c6', local: 'Brasil', localFlag: 'BR', visit: 'Escocia', visitFlag: 'GB-SCT', sede: 'Estadio Miami', hora: '2026-06-24T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'C' , apiFixtureId: 66456936, localApi: 'Brazil', visitApi: 'Scotland' },

    // --- GRUPO D ---
    { id: 'd1', local: 'Estados Unidos', localFlag: 'US', visit: 'Paraguay', visitFlag: 'PY', sede: 'Estadio Los Angeles', hora: '2026-06-12T18:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'D' , apiFixtureId: 66456940, localApi: 'United States', visitApi: 'Paraguay' },
    { id: 'd2', local: 'Australia', localFlag: 'AU', visit: 'Turquía', visitFlag: 'TR', sede: 'Estadio Vancouver', hora: '2026-06-13T21:00-07:00', sedeTimezone: 'America/Vancouver', fase: 'grupos', grupo: 'D' , apiFixtureId: 66456942, localApi: 'Australia', visitApi: 'Turkey' },
    { id: 'd3', local: 'Estados Unidos', localFlag: 'US', visit: 'Australia', visitFlag: 'AU', sede: 'Estadio Seattle', hora: '2026-06-19T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'D' , apiFixtureId: 66456944, localApi: 'United States', visitApi: 'Australia' },
    { id: 'd4', local: 'Turquía', localFlag: 'TR', visit: 'Paraguay', visitFlag: 'PY', sede: 'Estadio San Francisco', hora: '2026-06-19T20:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'D' , apiFixtureId: 66456946, localApi: 'Turkey', visitApi: 'Paraguay' },
    { id: 'd5', local: 'Turquía', localFlag: 'TR', visit: 'Estados Unidos', visitFlag: 'US', sede: 'Estadio Los Angeles', hora: '2026-06-25T19:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'D' , apiFixtureId: 66456948, localApi: 'Turkey', visitApi: 'United States' },
    { id: 'd6', local: 'Paraguay', localFlag: 'PY', visit: 'Australia', visitFlag: 'AU', sede: 'Estadio Seattle', hora: '2026-06-25T19:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'D' , apiFixtureId: 66456950, localApi: 'Paraguay', visitApi: 'Australia' },

    // --- GRUPO E ---
    { id: 'e1', local: 'Alemania', localFlag: 'DE', visit: 'Curazao', visitFlag: 'CW', sede: 'Estadio Houston', hora: '2026-06-14T12:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'E' , apiFixtureId: 66457070, localApi: 'Germany', visitApi: 'Curacao' },
    { id: 'e2', local: 'Costa de Marfil', localFlag: 'CI', visit: 'Ecuador', visitFlag: 'EC', sede: 'Estadio Philadelphia', hora: '2026-06-14T19:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'E' , apiFixtureId: 66457072, localApi: 'Ivory Coast', visitApi: 'Ecuador' },
    { id: 'e3', local: 'Alemania', localFlag: 'DE', visit: 'Costa de Marfil', visitFlag: 'CI', sede: 'Estadio Toronto', hora: '2026-06-20T16:00-04:00', sedeTimezone: 'America/Toronto', fase: 'grupos', grupo: 'E' , apiFixtureId: 66457074, localApi: 'Germany', visitApi: 'Ivory Coast' },
    { id: 'e4', local: 'Ecuador', localFlag: 'EC', visit: 'Curazao', visitFlag: 'CW', sede: 'Estadio Kansas City', hora: '2026-06-20T19:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'E' , apiFixtureId: 66457076, localApi: 'Ecuador', visitApi: 'Curacao' },
    { id: 'e5', local: 'Curazao', localFlag: 'CW', visit: 'Costa de Marfil', visitFlag: 'CI', sede: 'Estadio New York', hora: '2026-06-25T16:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'E' , apiFixtureId: 66457080, localApi: 'Curacao', visitApi: 'Ivory Coast' },
    { id: 'e6', local: 'Ecuador', localFlag: 'EC', visit: 'Alemania', visitFlag: 'DE', sede: 'Estadio Philadelphia', hora: '2026-06-25T16:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'E' , apiFixtureId: 66457078, localApi: 'Ecuador', visitApi: 'Germany' },

    // --- GRUPO F ---
    { id: 'f1', local: 'Países Bajos', localFlag: 'NL', visit: 'Japón', visitFlag: 'JP', sede: 'Estadio Dallas', hora: '2026-06-14T15:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'F' , apiFixtureId: 66456968, localApi: 'Netherlands', visitApi: 'Japan' },
    { id: 'f2', local: 'Suecia', localFlag: 'SE', visit: 'Túnez', visitFlag: 'TN', sede: 'Estadio Monterrey', hora: '2026-06-14T20:00-06:00', sedeTimezone: 'America/Monterrey', fase: 'grupos', grupo: 'F' , apiFixtureId: 66456970, localApi: 'Sweden', visitApi: 'Tunisia' },
    { id: 'f3', local: 'Países Bajos', localFlag: 'NL', visit: 'Suecia', visitFlag: 'SE', sede: 'Estadio Houston', hora: '2026-06-20T12:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'F' , apiFixtureId: 66456972, localApi: 'Netherlands', visitApi: 'Sweden' },
    { id: 'f4', local: 'Túnez', localFlag: 'TN', visit: 'Japón', visitFlag: 'JP', sede: 'Estadio Monterrey', hora: '2026-06-20T22:00-06:00', sedeTimezone: 'America/Monterrey', fase: 'grupos', grupo: 'F' , apiFixtureId: 66456974, localApi: 'Tunisia', visitApi: 'Japan' },
    { id: 'f5', local: 'Túnez', localFlag: 'TN', visit: 'Países Bajos', visitFlag: 'NL', sede: 'Estadio Dallas', hora: '2026-06-25T18:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'F' , apiFixtureId: 66456976, localApi: 'Tunisia', visitApi: 'Netherlands' },
    { id: 'f6', local: 'Japón', localFlag: 'JP', visit: 'Suecia', visitFlag: 'SE', sede: 'Estadio Guadalajara', hora: '2026-06-25T17:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'F' , apiFixtureId: 66456978, localApi: 'Japan', visitApi: 'Sweden' },

    // --- GRUPO G ---
    { id: 'g1', local: 'Bélgica', localFlag: 'BE', visit: 'Egipto', visitFlag: 'EG', sede: 'Estadio Seattle', hora: '2026-06-15T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'G' , apiFixtureId: 66456982, localApi: 'Belgium', visitApi: 'Egypt' },
    { id: 'g2', local: 'Irán', localFlag: 'IR', visit: 'Nueva Zelanda', visitFlag: 'NZ', sede: 'Estadio Los Angeles', hora: '2026-06-15T18:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'G' , apiFixtureId: 66456984, localApi: 'Iran', visitApi: 'New Zealand' },
    { id: 'g3', local: 'Bélgica', localFlag: 'BE', visit: 'Irán', visitFlag: 'IR', sede: 'Estadio Los Angeles', hora: '2026-06-21T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'G' , apiFixtureId: 66456986, localApi: 'Belgium', visitApi: 'Iran' },
    { id: 'g4', local: 'Nueva Zelanda', localFlag: 'NZ', visit: 'Egipto', visitFlag: 'EG', sede: 'Estadio Vancouver', hora: '2026-06-21T18:00-07:00', sedeTimezone: 'America/Vancouver', fase: 'grupos', grupo: 'G' , apiFixtureId: 66456988, localApi: 'New Zealand', visitApi: 'Egypt' },
    { id: 'g5', local: 'Egipto', localFlag: 'EG', visit: 'Irán', visitFlag: 'IR', sede: 'Estadio San Francisco', hora: '2026-06-26T20:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'G' , apiFixtureId: 66456992, localApi: 'Egypt', visitApi: 'Iran' },
    { id: 'g6', local: 'Nueva Zelanda', localFlag: 'NZ', visit: 'Bélgica', visitFlag: 'BE', sede: 'Estadio Seattle', hora: '2026-06-26T20:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'G' , apiFixtureId: 66456990, localApi: 'New Zealand', visitApi: 'Belgium' },

    // --- GRUPO H ---
    { id: 'h1', local: 'España', localFlag: 'ES', visit: 'Cabo Verde', visitFlag: 'CV', sede: 'Estadio Atlanta', hora: '2026-06-15T12:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'H' , apiFixtureId: 66456994, localApi: 'Spain', visitApi: 'Cape Verde' },
    { id: 'h2', local: 'Arabia Saudita', localFlag: 'SA', visit: 'Uruguay', visitFlag: 'UY', sede: 'Estadio Miami', hora: '2026-06-15T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'H' , apiFixtureId: 66456996, localApi: 'Saudi Arabia', visitApi: 'Uruguay' },
    { id: 'h3', local: 'España', localFlag: 'ES', visit: 'Arabia Saudita', visitFlag: 'SA', sede: 'Estadio Atlanta', hora: '2026-06-21T12:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'H' , apiFixtureId: 66456998, localApi: 'Spain', visitApi: 'Saudi Arabia' },
    { id: 'h4', local: 'Uruguay', localFlag: 'UY', visit: 'Cabo Verde', visitFlag: 'CV', sede: 'Estadio Miami', hora: '2026-06-21T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'H' , apiFixtureId: 66457000, localApi: 'Uruguay', visitApi: 'Cape Verde' },
    { id: 'h5', local: 'Cabo Verde', localFlag: 'CV', visit: 'Arabia Saudita', visitFlag: 'SA', sede: 'Estadio Houston', hora: '2026-06-26T19:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'H' , apiFixtureId: 66457004, localApi: 'Cape Verde', visitApi: 'Saudi Arabia' },
    { id: 'h6', local: 'Uruguay', localFlag: 'UY', visit: 'España', visitFlag: 'ES', sede: 'Estadio Miami', hora: '2026-06-26T20:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'H' , apiFixtureId: 66457002, localApi: 'Uruguay', visitApi: 'Spain' },

    // --- GRUPO I ---
    { id: 'i1', local: 'Francia', localFlag: 'FR', visit: 'Senegal', visitFlag: 'SN', sede: 'Estadio New York', hora: '2026-06-16T15:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'I' , apiFixtureId: 66457006, localApi: 'France', visitApi: 'Senegal' },
    { id: 'i2', local: 'Irak', localFlag: 'IQ', visit: 'Noruega', visitFlag: 'NO', sede: 'Estadio Boston', hora: '2026-06-16T18:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'I' , apiFixtureId: 66457008, localApi: 'Iraq', visitApi: 'Norway' },
    { id: 'i3', local: 'Francia', localFlag: 'FR', visit: 'Irak', visitFlag: 'IQ', sede: 'Estadio Philadelphia', hora: '2026-06-22T17:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'I' , apiFixtureId: 66457010, localApi: 'France', visitApi: 'Iraq' },
    { id: 'i4', local: 'Noruega', localFlag: 'NO', visit: 'Senegal', visitFlag: 'SN', sede: 'Estadio New York', hora: '2026-06-22T20:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'I' , apiFixtureId: 66457012, localApi: 'Norway', visitApi: 'Senegal' },
    { id: 'i5', local: 'Senegal', localFlag: 'SN', visit: 'Irak', visitFlag: 'IQ', sede: 'Estadio Toronto', hora: '2026-06-26T15:00-04:00', sedeTimezone: 'America/Toronto', fase: 'grupos', grupo: 'I' , apiFixtureId: 66457016, localApi: 'Senegal', visitApi: 'Iraq' },
    { id: 'i6', local: 'Noruega', localFlag: 'NO', visit: 'Francia', visitFlag: 'FR', sede: 'Estadio Boston', hora: '2026-06-26T15:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'I' , apiFixtureId: 66457014, localApi: 'Norway', visitApi: 'France' },

    // --- GRUPO J ---
    { id: 'j1', local: 'Argentina', localFlag: 'AR', visit: 'Argelia', visitFlag: 'DZ', sede: 'Estadio Kansas City', hora: '2026-06-16T20:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'J' , apiFixtureId: 66457018, localApi: 'Argentina', visitApi: 'Algeria' },
    { id: 'j2', local: 'Austria', localFlag: 'AT', visit: 'Jordania', visitFlag: 'JO', sede: 'Estadio San Francisco', hora: '2026-06-16T21:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'grupos', grupo: 'J' , apiFixtureId: 66457020, localApi: 'Austria', visitApi: 'Jordan' },
    { id: 'j3', local: 'Argentina', localFlag: 'AR', visit: 'Austria', visitFlag: 'AT', sede: 'Estadio Dallas', hora: '2026-06-22T12:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'J' , apiFixtureId: 66457022, localApi: 'Argentina', visitApi: 'Austria' },
    { id: 'j4', local: 'Jordania', localFlag: 'JO', visit: 'Argelia', visitFlag: 'DZ', sede: 'Estadio Kansas City', hora: '2026-06-22T22:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'J' , apiFixtureId: 66457024, localApi: 'Jordan', visitApi: 'Algeria' },
    { id: 'j5', local: 'Argelia', localFlag: 'DZ', visit: 'Austria', visitFlag: 'AT', sede: 'Estadio Monterrey', hora: '2026-06-27T20:00-06:00', sedeTimezone: 'America/Monterrey', fase: 'grupos', grupo: 'J' , apiFixtureId: 66457028, localApi: 'Algeria', visitApi: 'Austria' },
    { id: 'j6', local: 'Jordania', localFlag: 'JO', visit: 'Argentina', visitFlag: 'AR', sede: 'Estadio Guadalajara', hora: '2026-06-27T20:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'J' , apiFixtureId: 66457026, localApi: 'Jordan', visitApi: 'Argentina' },

    // --- GRUPO K ---
    { id: 'k1', local: 'Portugal', localFlag: 'PT', visit: 'R.D. Congo', visitFlag: 'CD', sede: 'Estadio Houston', hora: '2026-06-17T12:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'K' , apiFixtureId: 66457030, localApi: 'Portugal', visitApi: 'DR Congo' },
    { id: 'k2', local: 'Uzbekistán', localFlag: 'UZ', visit: 'Colombia', visitFlag: 'CO', sede: 'Estadio Azteca', hora: '2026-06-17T20:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'K' , apiFixtureId: 66457032, localApi: 'Uzbekistan', visitApi: 'Colombia' },
    { id: 'k3', local: 'Portugal', localFlag: 'PT', visit: 'Uzbekistán', visitFlag: 'UZ', sede: 'Estadio Monterrey', hora: '2026-06-23T11:00-06:00', sedeTimezone: 'America/Monterrey', fase: 'grupos', grupo: 'K' , apiFixtureId: 66457034, localApi: 'Portugal', visitApi: 'Uzbekistan' },
    { id: 'k4', local: 'Colombia', localFlag: 'CO', visit: 'R.D. Congo', visitFlag: 'CD', sede: 'Estadio Azteca', hora: '2026-06-23T20:00-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'K' , apiFixtureId: 66457036, localApi: 'Colombia', visitApi: 'DR Congo' },
    { id: 'k5', local: 'R.D. Congo', localFlag: 'CD', visit: 'Uzbekistán', visitFlag: 'UZ', sede: 'Estadio Guadalajara', hora: '2026-06-27T17:30-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'K' , apiFixtureId: 66457040, localApi: 'DR Congo', visitApi: 'Uzbekistan' },
    { id: 'k6', local: 'Colombia', localFlag: 'CO', visit: 'Portugal', visitFlag: 'PT', sede: 'Estadio Azteca', hora: '2026-06-27T17:30-06:00', sedeTimezone: 'America/Mexico_City', fase: 'grupos', grupo: 'K' , apiFixtureId: 66457038, localApi: 'Colombia', visitApi: 'Portugal' },

    // --- GRUPO L ---
    { id: 'l1', local: 'Inglaterra', localFlag: 'GB-ENG', visit: 'Croacia', visitFlag: 'HR', sede: 'Estadio Dallas', hora: '2026-06-17T15:00-05:00', sedeTimezone: 'America/Chicago', fase: 'grupos', grupo: 'L' , apiFixtureId: 66457042, localApi: 'England', visitApi: 'Croatia' },
    { id: 'l2', local: 'Ghana', localFlag: 'GH', visit: 'Panamá', visitFlag: 'PA', sede: 'Estadio Toronto', hora: '2026-06-17T19:00-04:00', sedeTimezone: 'America/Toronto', fase: 'grupos', grupo: 'L' , apiFixtureId: 66457044, localApi: 'Ghana', visitApi: 'Panama' },
    { id: 'l3', local: 'Inglaterra', localFlag: 'GB-ENG', visit: 'Ghana', visitFlag: 'GH', sede: 'Estadio Boston', hora: '2026-06-23T16:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'L' , apiFixtureId: 66457046, localApi: 'England', visitApi: 'Ghana' },
    { id: 'l4', local: 'Panamá', localFlag: 'PA', visit: 'Croacia', visitFlag: 'HR', sede: 'Estadio Toronto', hora: '2026-06-23T19:00-04:00', sedeTimezone: 'America/Toronto', fase: 'grupos', grupo: 'L' , apiFixtureId: 66457048, localApi: 'Panama', visitApi: 'Croatia' },
    { id: 'l5', local: 'Croacia', localFlag: 'HR', visit: 'Ghana', visitFlag: 'GH', sede: 'Estadio Boston', hora: '2026-06-27T17:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'L' , apiFixtureId: 66457052, localApi: 'Croatia', visitApi: 'Ghana' },
    { id: 'l6', local: 'Panamá', localFlag: 'PA', visit: 'Inglaterra', visitFlag: 'GB-ENG', sede: 'Estadio New York', hora: '2026-06-27T17:00-04:00', sedeTimezone: 'America/New_York', fase: 'grupos', grupo: 'L' , apiFixtureId: 66457050, localApi: 'Panama', visitApi: 'England' },

    // ==========================================
    // LLAVES ELIMINATORIAS COMPLETAS (32 Partidos)
    // ==========================================
    
    // --- 32AVOS DE FINAL (16 Partidos Completos) ---
    // ==========================================
    // RONDA DE 32 (M73-M88) - Plantilla oficial FIFA
    // ==========================================
    { id: '32_1', matchCode: 'M73', local: 'Canadá', localFlag: 'CA', visit: 'Sudáfrica', visitFlag: 'ZA', sede: 'Los Angeles Stadium', hora: '2026-06-28T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: '32avos', apiFixtureId: 53452545, localApi: 'Canada', visitApi: 'South Africa', localOrigen: '2B', visitOrigen: '2A', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_2', matchCode: 'M74', local: 'Alemania', localFlag: 'DE', visit: 'Paraguay', visitFlag: 'PY', sede: 'Boston Stadium', hora: '2026-06-29T16:30-04:00', sedeTimezone: 'America/New_York', fase: '32avos', apiFixtureId: 53452541, localApi: 'Germany', visitApi: 'Paraguay', localOrigen: '1E', visitOrigen: '3D', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_3', matchCode: 'M75', local: 'Países Bajos', localFlag: 'NL', visit: 'Marruecos', visitFlag: 'MA', sede: 'Monterrey Stadium', hora: '2026-06-29T19:00-06:00', sedeTimezone: 'America/Monterrey', fase: '32avos', apiFixtureId: 53452547, localApi: 'Netherlands', visitApi: 'Morocco', localOrigen: '1F', visitOrigen: '2C', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_4', matchCode: 'M76', local: 'Brasil', localFlag: 'BR', visit: 'Japón', visitFlag: 'JP', sede: 'Houston Stadium', hora: '2026-06-29T12:00-05:00', sedeTimezone: 'America/Chicago', fase: '32avos', apiFixtureId: 53452557, localApi: 'Brazil', visitApi: 'Japan', localOrigen: '1C', visitOrigen: '2F', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_5', matchCode: 'M77', local: 'Francia', localFlag: 'FR', visit: 'Suecia', visitFlag: 'SE', sede: 'New York New Jersey Stadium', hora: '2026-06-30T17:00-04:00', sedeTimezone: 'America/New_York', fase: '32avos', apiFixtureId: 53452543, localApi: 'France', visitApi: 'Sweden', localOrigen: '1I', visitOrigen: '3F', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_6', matchCode: 'M78', local: 'Costa de Marfil', localFlag: 'CI', visit: 'Noruega', visitFlag: 'NO', sede: 'Dallas Stadium', hora: '2026-06-30T12:00-05:00', sedeTimezone: 'America/Chicago', fase: '32avos', apiFixtureId: 53452561, localApi: 'Ivory Coast', visitApi: 'Norway', localOrigen: '2E', visitOrigen: '2I', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_7', matchCode: 'M79', local: 'México', localFlag: 'MX', visit: 'Ecuador', visitFlag: 'EC', sede: 'Estadio Azteca / Mexico City Stadium', hora: '2026-06-30T19:00-06:00', sedeTimezone: 'America/Mexico_City', fase: '32avos', apiFixtureId: 53452563, localApi: 'Mexico', visitApi: 'Ecuador', localOrigen: '1A', visitOrigen: '3E', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_8', matchCode: 'M80', local: 'Inglaterra', localFlag: 'GB-ENG', visit: 'R.D. Congo', visitFlag: 'CD', sede: 'Atlanta Stadium', hora: '2026-07-01T12:00-04:00', sedeTimezone: 'America/New_York', fase: '32avos', apiFixtureId: 53452565, localApi: 'England', visitApi: 'DR Congo', localOrigen: '1L', visitOrigen: '3K', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_9', matchCode: 'M81', local: 'Estados Unidos', localFlag: 'US', visit: 'Bosnia', visitFlag: 'BA', sede: 'San Francisco Bay Area Stadium', hora: '2026-07-01T17:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: '32avos', apiFixtureId: 53452553, localApi: 'United States', visitApi: 'Bosnia and Herzegovina', localOrigen: '1D', visitOrigen: '3B', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_10', matchCode: 'M82', local: 'Bélgica', localFlag: 'BE', visit: 'Senegal', visitFlag: 'SN', sede: 'Seattle Stadium', hora: '2026-07-01T13:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: '32avos', apiFixtureId: 53452555, localApi: 'Belgium', visitApi: 'Senegal', localOrigen: '1G', visitOrigen: '3I', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_11', matchCode: 'M83', local: 'Croacia', localFlag: 'HR', visit: 'Portugal', visitFlag: 'PT', sede: 'Toronto Stadium', hora: '2026-07-02T19:00-04:00', sedeTimezone: 'America/Toronto', fase: '32avos', apiFixtureId: 53452549, localApi: 'Croatia', visitApi: 'Portugal', localOrigen: '2L', visitOrigen: '2K', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_12', matchCode: 'M84', local: 'España', localFlag: 'ES', visit: 'Austria', visitFlag: 'AT', sede: 'Los Angeles Stadium', hora: '2026-07-02T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: '32avos', apiFixtureId: 53452551, localApi: 'Spain', visitApi: 'Austria', localOrigen: '1H', visitOrigen: '2J', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_13', matchCode: 'M85', local: 'Suiza', localFlag: 'CH', visit: 'Argelia', visitFlag: 'DZ', sede: 'BC Place Vancouver', hora: '2026-07-02T20:00-07:00', sedeTimezone: 'America/Vancouver', fase: '32avos', apiFixtureId: 53452505, localApi: 'Switzerland', visitApi: 'Algeria', localOrigen: '1B', visitOrigen: '3J', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_14', matchCode: 'M86', local: 'Argentina', localFlag: 'AR', visit: 'Cabo Verde', visitFlag: 'CV', sede: 'Miami Stadium', hora: '2026-07-03T18:00-04:00', sedeTimezone: 'America/New_York', fase: '32avos', apiFixtureId: 53452569, localApi: 'Argentina', visitApi: 'Cape Verde', localOrigen: '1J', visitOrigen: '2H', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_15', matchCode: 'M87', local: 'Colombia', localFlag: 'CO', visit: 'Ghana', visitFlag: 'GH', sede: 'Kansas City Stadium', hora: '2026-07-03T20:30-05:00', sedeTimezone: 'America/Chicago', fase: '32avos', apiFixtureId: 53452507, localApi: 'Colombia', visitApi: 'Ghana', localOrigen: '1K', visitOrigen: '3L', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '32_16', matchCode: 'M88', local: 'Australia', localFlag: 'AU', visit: 'Egipto', visitFlag: 'EG', sede: 'Dallas Stadium', hora: '2026-07-03T13:00-05:00', sedeTimezone: 'America/Chicago', fase: '32avos', apiFixtureId: 53452503, localApi: 'Australia', visitApi: 'Egypt', localOrigen: '2D', visitOrigen: '2G', fuenteBracket: 'fifa-current-2026-06-28' },
    { id: '16_1', matchCode: 'M89', local: 'Ganador 32_2', localFlag: '🏳️', visit: 'Ganador 32_5', visitFlag: '🏳️', sede: 'Philadelphia Stadium', hora: '2026-07-04T17:00-04:00', sedeTimezone: 'America/New_York', fase: '16avos' },
    { id: '16_2', matchCode: 'M90', local: 'Ganador 32_1', localFlag: '🏳️', visit: 'Ganador 32_3', visitFlag: '🏳️', sede: 'Houston Stadium', hora: '2026-07-04T12:00-05:00', sedeTimezone: 'America/Chicago', fase: '16avos' },
    { id: '16_3', matchCode: 'M91', local: 'Ganador 32_4', localFlag: '🏳️', visit: 'Ganador 32_6', visitFlag: '🏳️', sede: 'New York New Jersey Stadium', hora: '2026-07-05T16:00-04:00', sedeTimezone: 'America/New_York', fase: '16avos' },
    { id: '16_4', matchCode: 'M92', local: 'Ganador 32_7', localFlag: '🏳️', visit: 'Ganador 32_8', visitFlag: '🏳️', sede: 'Estadio Azteca / Mexico City Stadium', hora: '2026-07-05T18:00-06:00', sedeTimezone: 'America/Mexico_City', fase: '16avos' },
    { id: '16_5', matchCode: 'M93', local: 'Ganador 32_11', localFlag: '🏳️', visit: 'Ganador 32_12', visitFlag: '🏳️', sede: 'Dallas Stadium', hora: '2026-07-06T14:00-05:00', sedeTimezone: 'America/Chicago', fase: '16avos' },
    { id: '16_6', matchCode: 'M94', local: 'Ganador 32_9', localFlag: '🏳️', visit: 'Ganador 32_10', visitFlag: '🏳️', sede: 'Seattle Stadium', hora: '2026-07-06T17:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: '16avos' },
    { id: '16_7', matchCode: 'M95', local: 'Ganador 32_14', localFlag: '🏳️', visit: 'Ganador 32_16', visitFlag: '🏳️', sede: 'Atlanta Stadium', hora: '2026-07-07T12:00-04:00', sedeTimezone: 'America/New_York', fase: '16avos' },
    { id: '16_8', matchCode: 'M96', local: 'Ganador 32_13', localFlag: '🏳️', visit: 'Ganador 32_15', visitFlag: '🏳️', sede: 'BC Place Vancouver', hora: '2026-07-07T13:00-07:00', sedeTimezone: 'America/Vancouver', fase: '16avos' },

    // --- CUARTOS DE FINAL (M97-M100) ---
    { id: '4_1', matchCode: 'M97', local: 'Ganador 16_1', localFlag: '🏳️', visit: 'Ganador 16_2', visitFlag: '🏳️', sede: 'Boston Stadium', hora: '2026-07-09T16:00-04:00', sedeTimezone: 'America/New_York', fase: 'cuartos' },
    { id: '4_2', matchCode: 'M98', local: 'Ganador 16_5', localFlag: '🏳️', visit: 'Ganador 16_6', visitFlag: '🏳️', sede: 'Los Angeles Stadium', hora: '2026-07-10T12:00-07:00', sedeTimezone: 'America/Los_Angeles', fase: 'cuartos' },
    { id: '4_3', matchCode: 'M99', local: 'Ganador 16_3', localFlag: '🏳️', visit: 'Ganador 16_4', visitFlag: '🏳️', sede: 'Miami Stadium', hora: '2026-07-11T17:00-04:00', sedeTimezone: 'America/New_York', fase: 'cuartos' },
    { id: '4_4', matchCode: 'M100', local: 'Ganador 16_7', localFlag: '🏳️', visit: 'Ganador 16_8', visitFlag: '🏳️', sede: 'Kansas City Stadium', hora: '2026-07-11T20:00-05:00', sedeTimezone: 'America/Chicago', fase: 'cuartos' },

    // --- SEMIFINALES Y FINALES (M101-M104) ---
    { id: 'semi_1', matchCode: 'M101', local: 'Ganador 4_1', localFlag: '🏳️', visit: 'Ganador 4_2', visitFlag: '🏳️', sede: 'Dallas Stadium', hora: '2026-07-14T14:00-05:00', sedeTimezone: 'America/Chicago', fase: 'semis' },
    { id: 'semi_2', matchCode: 'M102', local: 'Ganador 4_3', localFlag: '🏳️', visit: 'Ganador 4_4', visitFlag: '🏳️', sede: 'Atlanta Stadium', hora: '2026-07-15T15:00-04:00', sedeTimezone: 'America/New_York', fase: 'semis' },
    { id: 'tercer_lugar', matchCode: 'M103', local: 'Perdedor S1', localFlag: '🏳️', visit: 'Perdedor S2', visitFlag: '🏳️', sede: 'Miami Stadium', hora: '2026-07-18T17:00-04:00', sedeTimezone: 'America/New_York', fase: 'final' },
    { id: 'gran_final', matchCode: 'M104', local: 'Ganador S1', localFlag: '🏳️', visit: 'Ganador S2', visitFlag: '🏳️', sede: 'New York New Jersey Stadium', hora: '2026-07-19T15:00-04:00', sedeTimezone: 'America/New_York', fase: 'final' }
];

window.partidosMundial = partidosMundial;
